spring:
  jpa:
    # enable query log with MySQL version
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # enable web console
  h2:
    console:
      enabled: true
  # load configs of yml
  profiles:
    include: oauth

